version: "3"
services:
  radarr:
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - /etc/radarr:/config
      - /mnt/shared/media/movies:/movies
      - /mnt/shared/torrents:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    image: linuxserver/radarr

  sonarr:
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - /etc/sonarr:/config
      - /mnt/shared/media/tv:/tv
      - /mnt/shared/torrents:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    image: linuxserver/sonarr

  jackett:
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - /etc/jackett:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    image: linuxserver/jackett

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - WEBUI_PORT=8080
    volumes:
      - /etc/qbittorrent:/config
      - /mnt/shared/torrents:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
